### PR TITLE
Fix timetable sync crash

### LINKED ISSUE #45: Błąd typu kaplica przekierowany z discord.
W szkolny.eu w wersji:
```
4.7.1+nightly.20210414
Wydanie Oficjalne
Tak
Dystrybucja
.APK
Data Kompilacji
Thu, 15 Apr 2021 01:44:54 +0200
```
Istnieje dziwny BUG który wywala aplikacje do błędu RIP ten błąd pojawił się po odblokowaniu telefonu z włączoną aplikacją szkolny.eu podajże na terminarzu
Crash jaki wywalił to:
```
Build version: 4.7.1+nightly.20210414 
Build date: 1981-01-01 01:01:02 
Current date: 2021-04-25 07:34:29 
Device: Motorola moto g(8) power 
OS version: Android 11 (SDK 30) 
 
Stack trace:
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
    at android.view.ViewGroup.addView(ViewGroup.java:5064)
    at android.view.ViewGroup.addView(ViewGroup.java:5004)
    at pl.szczodrzynski.edziennik.j.b.i.a.g2(TimetableDayFragment.kt:10)
    at pl.szczodrzynski.edziennik.j.b.i.a.b2(TimetableDayFragment.kt:1)
    at pl.szczodrzynski.edziennik.j.b.i.a$d$a.j(TimetableDayFragment.kt:6)
    at i.g0.j.a.a.e(ContinuationImpl.kt:3)
    at kotlinx.coroutines.s0.run(DispatchedTask.kt:19)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:250)
    at android.app.ActivityThread.main(ActivityThread.java:7755)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

User actions: 
2021-04-25 06:58:18: MainActivity created
2021-04-25 06:58:18: MainActivity resumed
2021-04-25 06:58:45: MainActivity paused
2021-04-25 07:34:15: MainActivity resumed
```
Crash zgłoszony przez przycisk ZGŁOŚ BŁĄD 
ScreenShoty:
obraz
obraz
~~Jak czegoś brakuje to proszę pisać na discord Greninja#5712~~ Jednak nie bo niektórzy mają ból dupy

### LINKED ISSUE #50: Błąd RIP po kliknięciu w powiadomienie
Po kliknięciu w powiadomienie (nowa wiadomość) wyskakuje błąd.
```
Build version: 4.8 
Build date: 1981-01-01 01:01:02 
Current date: 2021-05-31 15:30:18 
Device: HMD Global Nokia 6.2 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5106)
	at android.view.ViewGroup.addView(ViewGroup.java:4935)
	at android.view.ViewGroup.addView(ViewGroup.java:4875)
	at pl.szczodrzynski.edziennik.j.b.i.a.g2(TimetableDayFragment.kt:10)
	at pl.szczodrzynski.edziennik.j.b.i.a.b2(TimetableDayFragment.kt:1)
	at pl.szczodrzynski.edziennik.j.b.i.a$d$a.j(TimetableDayFragment.kt:6)
	at i.g0.j.a.a.e(ContinuationImpl.kt:3)
	at kotlinx.coroutines.s0.run(DispatchedTask.kt:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

User actions: 
2021-05-31 11:52:30: MainActivity created
2021-05-31 11:52:30: MainActivity resumed
2021-05-31 11:53:25: MainActivity paused
2021-05-31 11:53:27: MainActivity resumed
2021-05-31 11:53:31: MainActivity paused
2021-05-31 12:42:18: MainActivity resumed
2021-05-31 12:42:38: MainActivity paused
2021-05-31 12:43:37: MainActivity resumed
2021-05-31 12:43:38: MainActivity paused
2021-05-31 15:30:02: MainActivity resumed
```

### PR DESCRIPTION
**Pull request by doteq**
Closes #45 and closes #50. Please review carefully, I have no idea what i've done. But it works.

### CODE REVIEW

**Review by 6Arin9 — APPROVED** [review]
looks good

**Review by kuba2k2 — CHANGES_REQUESTED** [review]
Simple, but genius. Especially when no one knows how the problem started to exist in the first place. 

For a little explanation on what you've done: apparently sometimes removing just the `b.dayView` from the `dayFrame` has no effect. Then, trying to add the view to the container fails because of being added already, which makes totally no sense because it's theoretically been removed a line above. Calling `removeAllViews()` removes everything, including the `dayView` added previously and the `b.dayView` removed above.

Just while writing this review I realized something. See the bug already?

`b.dayView` is not the same as `dayView`. And that's how the problem started, thus how it needs to be resolved. Simply remove the `b.` in the `removeView()` call.

Anyway, huge thanks to this PR because I probably wouldn't have spotted this typo in the code and would try to come up with even more complicated workarounds for hours, just to finally notice those two chars.

Please change this and try it out, at least I think that my solution should work correctly.

**Comment by doteq** [comment]
Thank you for explaination, I updated the code referring to your solution. It didn't worked quite well, you still need to remove b.dayView at first render. I added a simple check which removes b.dayView at first render.

Wait, I'm just reading what I wrote and I realised something; Why don't I just remove dayView from layout file?

**Comment by doteq** [comment]
Okay, I think that this is a correct solution for this bug. There was unnecessary dayView in layout file. It was removed and replaced with new dayView at first render. When timetable was updated, code tried to delete dayView from layout file and not the new one, so app couldn't add view which led to a crash.

**Comment by kuba2k2** [comment]
Oh, right, so that `b.dayView` wasn't actually a typo at all. I remember, that at some point I was going to include something like yours parent check. Indeed, removing `dayView` from the layout may actually resolve the whole problem.

The question now is, why was the `dayView` in the layout in the first place?

Wait, I'm just checking the file's history for any explanation for this mystery, and I realised something. Looking at the old timetable code gives me headaches, so we'll probably stick with your solution; if it's stupid and it works, then it's not stupid.

**Comment by doteq** [comment]
I've checked the code, and only reference to layout's dayView was removing it, so I think that deleting it from layout file (which I did in my latest commit) would be the best solution.

**Review by kuba2k2 — APPROVED** [review]

**Pull request merged**
